# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.22 AS build-stage
WORKDIR /app
COPY . .

ARG SVC_GITHUB_ACCESS_TOKEN

# configuration to fetch private repos
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN git config --global \
  url."https://${SVC_GITHUB_ACCESS_TOKEN}@github.com".insteadof "https://github.com" \
  && go env -w GOPRIVATE="github.com/TimRutte"

COPY go.mod go.sum ./
RUN --mount=type=ssh go mod download
RUN --mount=type=ssh make tools
RUN make build-linux

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/api /app/config.yaml ./

USER nonroot:nonroot

ENTRYPOINT ["/api"]
